PACKAGE_NAME="sharp-drm"
PACKAGE_VERSION="2.0.0"

BUILT_MODULE_NAME[0]="sharp-drm"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make modules KERNELRELEASE=${kernelver} LINUX_DIR=/lib/modules/${kernelver}/build"
CLEAN="make clean_modules KERNELRELEASE=${kernelver} LINUX_DIR=/lib/modules/${kernelver}/build"

AUTOINSTALL="yes"
